---
cog_bundle_version: 4
name: netlify
description: Interact with Netlify
version: 0.0.20
author: Marc Campbell <marc.e.campbell@gmail.com>
docker: 
  image: marc/netlify-cog
  tag: latest
permissions:
  - netlify:read
commands:
  list:
    description: List recent deploys and statuses for a project
    executable: /home/bundle/bin/list
    rules:
      - when command is netlify:list must have netlify:read
  describe:
    description: List the current status of a project
    executable: /home/bundle/bin/describe
    rules:
      - when command is netlify:describe must have netlify:read
  sites:
    description: List all sites in the connected Netlify account
    executable: /home/bundle/bin/sites
    rules:
      - when command is netlify:sites must have netlify:read
templates:
  list:
    body: |
      | Is Current | Created At | Status | Commit Sha |
      |------------|------------|--------|------------| 
      ~each var=\$results~
      |~\$item.is_current~|~\$item.created_at~|~\$item.state~|~\$item.commit_ref~|
      ~end~
  describe:
    body: |
      \n
      **Name:** ~\$results[0].name~
      **Custom Domain:** ~\$results[0].custom_domain~
      **Last Deploy:** ~\$results[0].published_deploy_time~
      **Current Revision:** ~\$results[0].published_deploy_commit~
  sites:
    body: |
      | Name | Custom Domain | Last Updated |
      |------|---------------|--------------|
      ~each var=\$results~
      |~\$item.name~|~\$item.custom_domain~|~\$item.updated_at~|
      ~end~
    